### ISSUE TITLE
JNI ERROR

### ISSUE THREAD

**Issue by sienna011022** [unbound-tech/blockchain-crypto-mpc#18]
Hi I'm trying to build the project but I got a problem about "jni error" I already define   JAVA_HOME environment variable.Also I can find jni.h. I'm using ubuntu linux. I want to solve my problem  Could you please help me
![image](https://user-images.githubusercontent.com/90383376/144564390-b7e4a2c5-1c6b-40cf-8cf9-3ebccddcb7d4.png)
![image](https://user-images.githubusercontent.com/90383376/144564425-780ba382-5eb0-454f-aff1-caa76f035348.png)
![image](https://user-images.githubusercontent.com/90383376/144564448-f9b62cda-77ba-4f2f-b983-cf4a2c1b8892.png)

**Comment by Philamericus** [comment]
Hi @sienna011022. Sorry, this project is no longer supported. But, it looks like you just need to add the correct path for it. See [here](https://stackoverflow.com/questions/14529720/how-to-make-jni-h-be-found).
