### ISSUE TITLE
Can offer some example for android sample?

### ISSUE THREAD

**Issue by liupan163** [unbound-tech/blockchain-crypto-mpc#2]
Not see further code detail to how to achieve protect seed or key.
I am very interested in you project, please provider some examples~~

**Comment by liupan163** [comment]
how to use it? 
Can you provide a sample code project to show how to protect key or seed?

**Comment by Philamericus** [comment]
Hi. Thanks for contacting us. 

The project does not currently include sample usage for Android. We are looking into adding a sample for an Android crypto wallet in the near future.

The repository does include sample usage in both [C](https://github.com/unbound-tech/blockchain-crypto-mpc/blob/master/src/mpc_crypto_test.cpp) and [Python](https://github.com/unbound-tech/blockchain-crypto-mpc/blob/master/python/mpc_demo.py).

Let me know if those help you.
