### ISSUE TITLE
External API and documentation

### ISSUE THREAD

**Issue by Tony-Stark** [unbound-tech/blockchain-crypto-mpc#21]
In the README file it is stated that documentation will be available soon, and indeed, I didn't find the documentation, only the white paper, which is very valuable, but doesn't seem to include documentation of the library API itself. Also, I didn't find the API in C, only the source in c++. Considering that the library is said to be no longer maintained, will be able to see those things in the future?

**Comment by Philamericus** [comment]
Hi. On September 1, 2021 we stopped supporting this project, so unfortunately I don't have anyone from the project to answer your question. Sorry!
