### ISSUE TITLE
[Feature-request] Multiparty (t,n) ECDSA signatures

### ISSUE THREAD

**Issue by Ban44n** [unbound-tech/blockchain-crypto-mpc#3]
Hi,

There have been two new publications that allow multi-party (t,n) ECDSA signatures: One protocol by Steven Goldfeder et al. (2018) and one protocol by Yehuda Lindell et al. (2018). 

It might be worth looking into these schemes as it allows a more general setup of the wallet. I have put it as a feature request here 👍 

**Papers:**
https://eprint.iacr.org/2018/987.pdf
http://stevengoldfeder.com/papers/GG18.pdf

**Comment by oz-mishli** [comment]
Hi,

The multi-party ECDSA protocol by Yehuda Lindell et al. (2018) is implemented in Unbound commercial offerings; these include many additional capabilities on top of the protocol, such as offline approval, cryptographically enforced risk-based policies and more. Further details are available [here](https://www.unboundtech.com/cryptoasset-security-platform/packages/). Kindly let us know should you have further questions.

**Comment by Wahahahahahahahahahaha** [comment]
Hi,
Recently have read the white paper of the blockchain-crypto-mpc library, but I still confused about that how to use BIP-Key-Derivation to output the Shared private keys x1 and x2 of wallet private keys x. I want to know hou to implementation 2-party BIP32 of the library? Looking forward to your reply, thanks

**Comment by TovaD** [comment]
Hi, 
Please open in a new issue and I will be happy to direct the relevant team member to address your question there. 

Thanks, 

Tova Dvorin, Community Manager @ Unbound Tech

**Comment by Wahahahahahahahahahaha** [comment]
ok Thanks
