### ISSUE TITLE
MPCCrypto_verifyEcdsa curve type hardcoded to k256.

### ISSUE THREAD

**Issue by Kevin-Jiang78** [unbound-tech/blockchain-crypto-mpc#5]
crypto::ecurve_t curve = crypto::curve_k256;  //line 324 blockchain-crypto-mpc/src/mpc_crypto_ecdsa.cpp

**Comment by peer-guy** [comment]
Indeed, at this time we have hard coded this specific curve for API simplicity.
The protocols and implementation are curve agnostic, though.
What other curves would you find interesting in the context of blockchain ?

**Comment by Kevin-Jiang78** [comment]
Got it. Just got trouble to validate P256 certificate. Thanks a lot.
