### ISSUE TITLE
Clarify patent situation

### ISSUE THREAD

**Issue by ysangkok** [unbound-tech/blockchain-crypto-mpc#6]
Is any code in this repository covered by [this patent](https://patents.google.com/patent/WO2018211676A1/en) or any other patents?

**Comment by oz-mishli** [comment]
Hi Janus,

The code in this repository is protected by several pending patents (not the one noted in your question though) — however, as long as you’re using the repository according to the library’s license (GPL 3.0), there is no issue in this perspective. 

Thanks,
Oz

**Comment by Wahahahahahahahahahaha** [comment]
Hi，
Have your team published patents for this library? I want to know more deeply how do you implement it that Protecting cryptographic signing keys and seed secrets with Multi-Party Computation. 
thanks，
