### ISSUE TITLE
Build problem and wasm)

### ISSUE THREAD

**Issue by Harzu** [unbound-tech/blockchain-crypto-mpc#7]
Hi, i need help for building lib

I apologize in advance for the stupid questions, I am not strong in c ++
i use directions for build of the build.md and i get an error

```shell
c++ -O2 -fPIC -fno-strict-aliasing -Wno-unused -Wno-switch -Wno-switch-enum -Werror -mpclmul -std=c++0x -DMPC_CRYPTO_NO_JNI -DMPC_CRYPTO_EXPORTS -fvisibility=hidden -maes -I include -I /include -I /include/linux -I src/utils -I src/crypto_utils -I src/mpc_protocols -o src/utils/precompiled.h.gch -c src/utils/precompiled.h
clang: error: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Werror,-Wdeprecated]
make: *** [src/utils/precompiled.h.gch] Error 1
```
Has anyone come across this?

And second question)

i can compile this library into wasm?
i try compile but i always get errors because at first i need compile this lib

I would like to know right away whether to spend the effort or is it unrealistic, like some libraries on Rust

**my platform macos**

**Comment by Philamericus** [comment]
Hi Harzu,

Are you using the source/project provided in the [MacOS directory](https://github.com/unbound-tech/blockchain-crypto-mpc/tree/master/macos)? It should compile for you without any issues.
